version: 2.1

orbs:
  python: circleci/python@2.0.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run: 
          command: |
            python3 -m unittest TestTriangle.py
      - store_artifacts:
          path: ./test-results/results.xml
      - store_test_results:
          path: ./test-results

workflows:
  sample:
    jobs:
      - build-and-test